\subsection[except]{Exceptions}

\begin{frame}[fragile]
  \frametitlecpp[98]{Exceptions}
  \begin{block}{The concept}
    \begin{itemize}
      \item to handle \textit{exceptional} events that happen rarely
      \item and cleanly jump to a place where the error can be handled
    \end{itemize}
  \end{block}
  \begin{block}{In practice}
    \begin{itemize}
      \item add an exception handling block with \mintinline{cpp}{try} ... \mintinline{cpp}{catch}
      \begin{itemize}
        \item when exceptions are possible \textit{and can be handled}
      \end{itemize}
      \item throw an exception using \mintinline{cpp}{throw}
      \begin{itemize}
        \item when a function cannot proceed or recover internally
      \end{itemize}
    \end{itemize}
  \end{block}
  \begin{multicols}{2}
    \begin{cppcode*}{fontsize=\scriptsize,gobble=2}
      #include <stdexcept>
      ...
      try {
        process_stream_data(s);
      } catch (const range_error& e) {
        cerr << e.what() << endl;
      }
    \end{cppcode*}
    \columnbreak
    \begin{cppcode*}{fontsize=\scriptsize,gobble=2}
      void process_stream_data(stream &s) {
        ...
        if (data_location >= buffer.length()) {
          throw range_error{"buf overflow"};
        }
        ...
      }
    \end{cppcode*}
  \end{multicols}
\end{frame}

\begin{frame}[fragile]
  \frametitlecpp[98]{Exceptions}
  \begin{block}{Rules and behavior}
    \begin{itemize}
      \item objects of any type can be thrown
      \begin{itemize}
        \item prefer standard exception types from the \texttt{<stdexcept>} header
        \item define your own subclass of \mintinline{cpp}{std::exception} if needed
      \end{itemize}
      \item an exception will be caught if the type in the catch clause matches or is a base class of the thrown object's static type
      \begin{itemize}
          \item if no one catches an exception then \mintinline{cpp}{std::terminate} is called
      \end{itemize}
      \item you can have multiple catch clauses, will be matched in order
      \item all objects on the stack between the \mintinline{cpp}{throw} and the \mintinline{cpp}{catch} are destructed automatically during stack unwinding
      \begin{itemize}
        \item this should cleanly release intermediate resources
        \item make sure you are using the RAII idiom for your own classes
      \end{itemize}
    \end{itemize}
  \end{block}
\end{frame}

\begin{frame}[fragile]
  \frametitlecpp[17]{Exceptions}
  \begin{block}{Advice}
    \begin{itemize}
      \item throw exceptions by value, catch them by (const) reference
      \item use exceptions for \textit{unlikely} runtime errors outside the program's control
      \begin{itemize}
        \item  bad inputs, files unexpectedly not found, DB connection, \ldots
      \end{itemize}
      \item \textit{don't} use exceptions for logic errors in your code
      \begin{itemize}
        \item consider \mintinline{cpp}{assert} and tests
      \end{itemize}
      \item \textit{don't} use exceptions to provide alternative return values (or to skip them)
      \begin{itemize}
        \item you can use \mintinline{cpp}{std::optional} or \mintinline{cpp}{std::variant}
        \item avoid using the global C-style \mintinline{cpp}{errno}
      \end{itemize}
      \item See also the \href{https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#S-errors}{\cpp core guidelines} and the \href{https://isocpp.org/wiki/faq/exceptions}{ISO \cpp FAQ}
    \end{itemize}
  \end{block}
\end{frame}

\begin{frame}[fragile]
  \frametitlecpp[98]{Exceptions}
  \begin{block}{A more illustrative example}
    \begin{itemize}
      \item exceptions are very powerful when there are many calls / lines of code between the error and where the error is handled
      \item they can also rather cleanly handle different types of errors
      \item \textit{try ... catch} statements can also be nested
    \end{itemize}
  \end{block}
  \begin{multicols}{2}
    \begin{cppcode*}{fontsize=\scriptsize,gobble=2}
      try {
        for (const &file : files) {
          try {
            process_file(file);
          }
          catch (const file_bad &e) {
            ... // Skips one file
          }
        }
      } catch (const db_bad &e) {
        ... // This exception
            // aborts everything
      }
    \end{cppcode*}
    \columnbreak
    \begin{cppcode*}{fontsize=\scriptsize,gobble=2}
      int process_file(const fileobj &file) {
        ...
        if (fh = open_file(file)) {
          throw
            file_bad(file.error.reason());
        }
        while (!fh) {
          line = read_line(fh);
          add_line_to_db(line); // Can throw
                                // db_bad
        }
        return 0;
      }
    \end{cppcode*}
  \end{multicols}
\end{frame}

\begin{frame}[fragile]
  \frametitlecpp[98]{Exceptions}
  \begin{block}{Catching everything}
    \begin{itemize}
    \item sometimes we need to catch all possible exceptions
    \item e.g. in \mintinline{cpp}{main}, a thread, a destructor, interfacing with C, \ldots
    \end{itemize}
  \end{block}
  \begin{cppcode}

    try {
      callUnknownFramework();
    } catch(const std::exception& e) {
      // catches std::exception and all derived types
      std::cerr << "Exception: " << e.what() << std::endl;
    } catch(...) {
      // catches everything else
      std::cerr << "Unknown exception type" << std::endl;
    }
  \end{cppcode}
\end{frame}

\begin{frame}[fragile]
  \frametitlecpp[98]{Error Handling and Exceptions}
  \begin{block}{}
    \begin{itemize}
      \item exceptions have little cost if no exception is thrown
      \begin{itemize}
        \item so they are recommended for \textit{exceptional} events
      \end{itemize}
      \item however, in a tight, performance-critical loop, where the error is handled close to the place it happens a more explicit error code or object might be better
      \begin{itemize}
        \item but profile if you really want to find out!
      \end{itemize}
   \end{itemize}
  \end{block}
  \begin{multicols}{2}
    \begin{minipage}{4.5cm}
      \begin{alertblock}{Don't}
        \begin{cppcode*}{fontsize=\tiny,gobble=2,linenos=false}
          // try ... catch in hot loop might
          //    impact performance
          for (const &item: list) {
            try {
              check_item(item); // Can throw
              ... // process item
            }
            catch (bad_item &e) {
              ... // ignore and keep going
            }
          }
        \end{cppcode*}
      \end{alertblock}
    \end{minipage}
    \columnbreak
    \begin{minipage}{5.8cm}
      \begin{exampleblock}{Do}
        \begin{cppcode*}{fontsize=\tiny,gobble=2,linenos=false}
          // For this code, explicit error codes
          //   may be better
          for (const &item: list) {
            std::optional<T> err_code = check_item(item);
            if (!err_code) {
              ... // process item
            } else {
              ... // warn and carry on
            }
          }
        \end{cppcode*}
      \end{exampleblock}
    \end{minipage}
  \end{multicols}
\end{frame}


\begin{frame}[fragile]
  \frametitlecpp[11]{noexcept specifier}
  \begin{block}{}
    \begin{itemize}
      \item a function with the \mintinline{cpp}{noexcept} specifier states that it guarantees to not throw an exception
      \begin{cppcode*}{gobble=2,linenos=false}
        int f() noexcept;
      \end{cppcode*}
      \begin{itemize}
        \item either no exceptions will be thrown or they are handled internally
        \item checked at compile time, so it allows the compiler to optimise around that knowledge
      \end{itemize}
      \item a function with \mintinline{cpp}{noexcept(expression)} is only \mintinline{cpp}{noexcept} when \mintinline{cpp}{expression} evaluates to \mintinline{cpp}{true} at compile-time
      \begin{cppcode*}{gobble=2,linenos=false}
        int safe_if_8B_long() noexcept(sizeof(long)==8);
      \end{cppcode*}
      \item Use \mintinline{cpp}{noexcept} on leaf functions where you know the behaviour
      \item C++11 destructors are \mintinline{cpp}{noexcept} - never throw from them
    \end{itemize}
  \end{block}
\end{frame}


\begin{frame}[fragile]
  \frametitlecpp[11]{noexcept operator}
  \begin{block}{}
    \begin{itemize}
      \item the \mintinline{cpp}{noexcept(expression)} operator checks at compile-time whether an expression can throw exceptions
      \item it returns a \mintinline{cpp}{bool}, which is \mintinline{cpp}{true} if no exceptions can be thrown
    \end{itemize}
  \end{block}
  \begin{block}{}
    \begin{cppcode*}{gobble=2, linenos=false}
      constexpr bool callCannotThrow = noexcept(f());
      if constexpr (callCannotThrow) { ... }
    \end{cppcode*}
  \end{block}
  \begin{block}{}
    \begin{cppcode*}{gobble=2, linenos=false}
      template <typename Function>
      void g(Function f) noexcept(noexcept(f())) {
        ...
        f();
      }
    \end{cppcode*}
  \end{block}
\end{frame}
